{
 "title": "Deluge Metrics 2",
 "description": "A Deluge statistics dashboard",
 "tags": [
  "deluge",
  "system"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Total Torrents",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deluge_torrents{state=\"total\"}"
    }
   ]
  },
  {
   "title": "Active",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deluge_torrents{state=\"active\"}"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deluge_torrents{state=\"error\"}"
    }
   ]
  },
  {
   "title": "Downloading",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deluge_torrents{state=\"downloading\"}"
    }
   ]
  },
  {
   "title": "Seeding",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deluge_torrents{state=\"seeding\"}"
    }
   ]
  },
  {
   "title": "Paused",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deluge_torrents{state=\"paused\"}"
    }
   ]
  },
  {
   "title": "Current ratio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deluge_libtorrent_net_sent_payload_bytes_total/deluge_libtorrent_net_recv_payload_bytes_total"
    }
   ]
  },
  {
   "title": "Total download",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "deluge_libtorrent_net_recv_payload_bytes_total"
    }
   ]
  },
  {
   "title": "Total upload",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "deluge_libtorrent_net_sent_payload_bytes_total"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deluge_libtorrent_peer_num_peers_connected"
    }
   ]
  },
  {
   "title": "DHT Peers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deluge_libtorrent_dht_dht_peers"
    }
   ]
  },
  {
   "title": "PEX In+Out",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deluge_libtorrent_ses_num_incoming_pex_total + deluge_libtorrent_ses_num_outgoing_pex_total"
    }
   ]
  },
  {
   "title": "Bandwidth Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(deluge_libtorrent_net_recv_payload_bytes_total[5m])",
     "legendFormat": "Download"
    },
    {
     "expr": "irate(deluge_libtorrent_net_sent_payload_bytes_total[5m])",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "deluge_libtorrent_peer_num_peers_connected",
     "legendFormat": "peers_connected"
    },
    {
     "expr": "deluge_libtorrent_utp_num_utp_connected",
     "legendFormat": "utp_connected"
    }
   ]
  },
  {
   "title": "DHT",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "deluge_libtorrent_dht_dht_nodes",
     "legendFormat": "DHT Nodes"
    },
    {
     "expr": "deluge_libtorrent_dht_dht_peers",
     "legendFormat": "DHT Peers"
    }
   ]
  },
  {
   "title": "Torrents by label",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deluge_torrents_by_label{label=\"\"}",
     "legendFormat": "no_label"
    },
    {
     "expr": "deluge_torrents_by_label{label!=\"\"}",
     "legendFormat": "{{label}}"
    }
   ]
  }
 ]
}